substitutions:
  _REGION: europe-west1
  _SERVICE: expense-tracker-api
  _REPOSITORY: expense-tracker
  _IMAGE: api
  _GOOGLE_CLIENT_ID: replace-with-google-client-id
  _ALLOWED_ORIGINS: https://replace-with-frontend-origin
  _GOOGLE_REDIRECT_URI: https://expensetracker-git-178545711969.europe-west1.run.app

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},ALLOWED_ORIGINS=${_ALLOWED_ORIGINS},GOOGLE_REDIRECT_URI=${_GOOGLE_REDIRECT_URI},COOKIE_SECURE=true
      - --set-secrets=GOOGLE_CLIENT_SECRET=google-client-secret:latest,TOKEN_ENCRYPTION_KEY=expense-token-encryption-key:latest

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$SHORT_SHA